# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  engine_config = debug
  application_config = debug

else ifeq ($(config),release)
  engine_config = release
  application_config = release

else ifeq ($(config),dist)
  engine_config = dist
  application_config = dist

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := engine application

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

engine:
ifneq (,$(engine_config))
	@echo "==== Building engine ($(engine_config)) ===="
	@${MAKE} --no-print-directory -C engine -f Makefile config=$(engine_config)
endif

application: engine
ifneq (,$(application_config))
	@echo "==== Building application ($(application_config)) ===="
	@${MAKE} --no-print-directory -C application -f Makefile config=$(application_config)
endif

clean:
	@${MAKE} --no-print-directory -C engine -f Makefile clean
	@${MAKE} --no-print-directory -C application -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo "  dist"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   engine"
	@echo "   application"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"